name: Execute unit-tests
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'
      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --no-restore --verbosity normal --logger:"trx;LogFileName=test-results.trx" --results-directory ${{ github.workspace }}/results
#        run: dotnet test ./WebActionsTests/MoreTests.csproj --no-restore --verbosity normal --logger:"trx;LogFileName=more-tests-results.trx" --results-directory ${{ github.workspace }}/results
      

      - name: Create test summary
        uses: dorny/test-reporter@v2
        with:
          name: Unit tests report
          reporter: dotnet-trx
          path: ${{ github.workspace }}/results/*.trx
        if: always()
