name: Execute unit-tests
on:
  workflow_dispatch
  pull_request:
    branches:
      - main
jobs:
  steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'